name: Build and Test Docker Image

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: null

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t stoic_quotes .

    - name: Run Docker
      run: docker run -d --name stoic_quotes -p 3000:3000 stoic_quotes

    - name: Display Docker container logs
      run: docker logs stoic_quotes

    - name: Test Docker
      run: curl --fail localhost:3000/ || exit 1

