name: Build and Test Docker Image

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: null

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t stoic_quotes .

    - name: Test Docker image
      run: |
        docker run -d --name stoic_quotes -p 3000:3000 stoic_quotes
        sleep 30 # Wait for the application to start
        curl --fail localhost:3000/ || exit 1

